### ISSUE TITLE
Wattsi version number is now hard-coded into the source

### ISSUE THREAD

**Issue by domenic** [whatwg/wattsi#102]
I am not super-happy with how https://github.com/whatwg/wattsi/commit/262a908783986fb90843dbe95085fa7ac05a2924 solved https://github.com/whatwg/html-build/issues/157. I think it silenced the warning but didn't fix the underlying problem, and now it's causing extra maintenance work on all Wattsi PRs.

Personally I would prefer to keep the warning by rolling back that commit. Even if we don't do that, we should have a tracking issue for solving this in a better way.

As an example of a better way, we could send the number of commits from outside the Docker container into the Docker container via environment variables, and then have the Wattsi build process pick that up.

**Comment by sideshowbarker** [comment]
I’m fine with the change being rolled back. I agree it’s not the optimal fix.

> now it's causing extra maintenance work on all Wattsi PRs

My thinking had just been that we only update the Wattsi sources relatively infrequently, and so bumping the version number when we do change the source would not be a big deal.

**Comment by annevk** [comment]
I prefer not rolling it back as although this is slightly more work at times, it at least prevents the confusion people have had with the log output. And we don't even have to change the fallback version number in wattsi each time I think, only when there's a breaking change.

**Comment by domenic** [comment]
Fixed by https://github.com/whatwg/wattsi/commit/ddbc7f1e369fb030d4e5a26f5dfb3395c1cdbabc; I had the wrong issue number in that commit, oops.
