### ISSUE TITLE
Warn about unused references

### ISSUE THREAD

**Issue by foolip** [whatwg/wattsi#16]
With https://github.com/whatwg/html/issues/585 it became apparent that there are many unused references, left behind be mistake over the years.

The README says "Strip out unused references" (added by @sideshowbarker) and it would be nice if in addition to stripping them, wattsi also warns about them so that they can be removed.

Once there are no unused references in the HTML spec, perhaps it could simply be an error instead.

**Comment by foolip** [comment]
@Hixie @sideshowbarker, where it "Strip out unused references" implemented? My Pascal skills are limited.

**Comment by sideshowbarker** [comment]
> @Hixie @sideshowbarker, where it "Strip out unused references" implemented? My Pascal skills are limited.

As far as I can tell from inspecting the code, the `dt` element in the reference is handled at https://github.com/whatwg/wattsi/blob/1b6b1cc6c96a024d3af7a89160d1d2c60a4ac5e4/src/wattsi.pas#L768 and the `dd` element in the reference is handled at https://github.com/whatwg/wattsi/blob/1b6b1cc6c96a024d3af7a89160d1d2c60a4ac5e4/src/wattsi.pas#L777

And those both set the return value for the `ProcessNode` function to `False` if they are part of an unused reference.

 `ProcessNode` is at  https://github.com/whatwg/wattsi/blob/1b6b1cc6c96a024d3af7a89160d1d2c60a4ac5e4/src/wattsi.pas#L468 and the comment there says, `return True if we are to keep this node, False if we drop it`, so the final effect is that those nodes from the source are (silently) dropped in the output.

So I think as far as this issue goes, adding a `Warn(…)` in one or both of the `if (not References.Has(LastSeenReferenceName)) then … Result := False;` blocks for those two cases would have the desired effect.
