### ISSUE TITLE
Incorrect exit status with invalid args

### ISSUE THREAD

**Issue by abhillman** [whatwg/wattsi#163]
**Observed**: if zero or invalid args are provided, `wattsi` exits with a zero status code
**Expected**: exit with a non-zero status code

Caveat: this may or may not be wise to fix due to potentialities of it breaking an existing upstream caller

**Comment by domenic** [comment]
Dupe of https://github.com/whatwg/wattsi/issues/77.

No worries about upstream callers; we control them all.
