### ISSUE TITLE
Characters need to be URL-encoded in fragments

### ISSUE THREAD

**Issue by izh1979** [whatwg/wattsi#22]
Currently the spec contains following link: \<a href=#shared-internal-slot:-[[crossoriginpropertydescriptormap]]>...\</a>. But according to the spec the square brackets must be URL-encoded.

**Comment by zcorpan** [comment]
Thank you for reporting this! It should be `#shared-internal-slot:-crossoriginpropertydescriptormap` the next time the spec is generated.

**Comment by izh1979** [comment]
Welcome. :-)
