### ISSUE TITLE
Allowing new images to be added

### ISSUE THREAD

**Issue by domenic** [whatwg/wattsi#3]
See https://github.com/whatwg/html/pull/132#issuecomment-139376502

Code is at https://github.com/whatwg/wattsi/blob/fc38b65c0f2f45065db6f702e3a0408d7a886bc3/src/wattsi.pas#L60-L61 and https://github.com/whatwg/wattsi/blob/fc38b65c0f2f45065db6f702e3a0408d7a886bc3/src/wattsi.pas#L757-L782

Solutions:

1. Leave as-is and get credentials for images.whatwg.org and change the deploy script. Pros: helps spread the load out to multiple servers. So, possibly best for readers. Cons: more complicated and less transparent deploy script, and more servers to administer.
2. Change source references to /images/ instead and remove rewriting code. Pros: no rewriting needed anymore. No longer need to host images in both singlepage and multipage, and can 301 the multipage copies. Cons: absolute URLs involve making assumptions; the spec works pretty well otherwise when mounted in a subdirectory.
3. Remove rewriting code and leave source as-is. Pros: probably most seamless for spec authors and script maintainers. Cons: we continue duplicating the images in singlepage and multipage.
4. Change rewriting code to rewrite multipage to ../images. Pros: no double image hosting; pretty easy to maintain. Cons: requires lots of Wattsi knowledge.

Leaning toward (3) but they all are pretty good.

**Comment by sideshowbarker** [comment]
I prefer (3) as well, for the reason that as noted it’s the most seamless for spec authors and less costly and potentially error-prone than touching the Wattsi code

**Comment by annevk** [comment]
We have already done 2 for `404.html`.
