### ISSUE TITLE
Changes to wattsi are not live

### ISSUE THREAD

**Issue by zcorpan** [whatwg/wattsi#37]
Is there some manual step necessary for changes to wattsi to affect https://html.spec.whatwg.org/ ?

https://github.com/whatwg/wattsi/commit/ea02b683c17ef0945f968441de517f5f5508c2e8 seems to not have been used when building https://github.com/whatwg/html/commit/123b42ece34482e8d21d7210eef6ce4709214207

@domenic ?

**Comment by domenic** [comment]
Yes, https://github.com/domenic/wattsi-server does not update automatically, sorry about that :(. We can leave this open to track me doing that somehow.

**Comment by domenic** [comment]
Oh, and I guess @annevk has noted that the build server does not update correctly, despite our web hooks trying to do so.

**Comment by annevk** [comment]
Yeah, the Webhook output is
```

compile: mode=RELEASE main=wattsi testcmd=bin/wattsi defines=-dUSEROPES -dLINES -dPARSEERROR
compile: COMPILING - RELEASE MODE
Target OS: Linux for x86-64
Compiling wattsi.pas
Fatal: Can't find unit system used by wattsi
Fatal: Compilation aborted
Error: /home/annevankesteren/htmlbuild/fpc-3.0.0/bin/ppcx64 returned an error exitcode
```
while when you invoke the script directly you get a totally different output. Could it be `chmod`?

**Comment by annevk** [comment]
Should we add an additional Webhook for build.whatwg.org or put build.whatwg.org on the same server as html.spec.whatwg.org?

**Comment by domenic** [comment]
> Yeah, the Webhook output is

Interesting. Maybe PATH differences, if it's using the PATH to find the unit system? Not chmod; I just checked that.

> Should we add an additional Webhook for build.whatwg.org or put build.whatwg.org on the same server as html.spec.whatwg.org?

We originally tried that but it caused the server to run out of memory and reboot due to high usage, thus taking down the spec and all other specs hosted there -_-. I just need to add a webhook. But I don't have Apache on the build server so it'll be a bit of work.

**Comment by annevk** [comment]
http://wiki.freepascal.org/Unit_not_found_-_How_to_find_units gives some advice, but passing -vut to where fpc is called (`wattsi/src/lib/compile.sh`) doesn't change the output for me.

**Comment by domenic** [comment]
This is fixed by the new Docker-based build system. You can see in https://travis-ci.org/whatwg/html/builds/270491769 that it detected a changed Wattsi and recompiled it. (It will then upload the new version to Docker hub for future work.)

\o/!
