### ISSUE TITLE
Allow removing navigation to previous and next page from multipage specs

### ISSUE THREAD

**Issue by tobie** [whatwg/wattsi#65]
Now that we're using Wattsi to build spec previews and HTML diffs, keeping the navigation around is quite confusing as it points to 404s.

It would be ideal to have an option to disable it that wattsi-server could trigger.

**Comment by domenic** [comment]
Why would it point to 404s? Are the previews and diffs incomplete?

In general I'd rather keep the previews closer to the source material instead of different from them.

**Comment by tobie** [comment]
That's a good point.

I was only uploading the files that had been modified.

I'm now uploading everything.
