### ISSUE TITLE
Add the ability to substitute in a year

### ISSUE THREAD

**Issue by domenic** [whatwg/wattsi#66]
In order to change the copyright license, it would be ideal if we could get the copyright year to update every time we build, instead of manually.

I thought Wattsi's existing PUBDATE business would help with this, but no, that seems to be hard-coded into a particular date format: https://github.com/whatwg/wattsi/blob/78e3fd236bfe0806fa098d718345b07ad1189706/src/wattsi.pas#L853

Probably we should just add a `<span class="pubyear">` handler very similar to that block of code. Probably we'll want to move the DecodeDate line up a bit so it's shared between them.

I can work on this, but if someone else wants to take it, let me know.

**Comment by foolip** [comment]
Fixed by https://github.com/whatwg/wattsi/pull/67.
