### ISSUE TITLE
Passing --quiet ignores errors

### ISSUE THREAD

**Issue by domenic** [whatwg/wattsi#9]
For example, I can send the original non-preprocessed HTML source file through wattsi --quiet without any errors. This seems bad.

**Comment by sideshowbarker** [comment]
Yeah it’s bad, and definitely unintentional. Will investigate.

**Comment by sideshowbarker** [comment]
Actually, I can’t reproduce this now (after building for current master). When you have time can you please check again and lemme know if you observe the same problem again? And if so and you have a test case that triggers the problem, it would be great to have that. (I tried myself with introducing parse errors into the source, as well as dfn-xref errors—but in neither case did `--quiet` cause those errors to be suppressed.)

**Comment by domenic** [comment]
Yeah I can't reproduce this anymore either. Maybe it was the build server in the bad old days or something....
